Display post Ticket #27
100devs/course-tracker pull request #45
Opened 2021-08-30 21:08 UTC by AshtarCodes

In this Post component, we've set it up with the idea that the editing function will be a "live edit". It's at a basic stage and we are expecting some feedback. Right now, it is rendering a title from a "mockPost" object and the post body is being imported into the Content.mdx file and passed into the Post.js component as a prop (children).

We need clarification around a few things:

1. We are wondering how data will be passed from MDX markdown to JSON and back to MD when creating, and editing posts. Will that require some sort of config, like a YAML file? 
- This is also something we will explore in the MDX docs. 

2. Do we need a dedicated Header component?
- we weren't sure so we left it as a header element for now. 

3.  We haven't styled the components. We figured we should establish some sort of standard as a group, and create styling specific tickets. What do you think?

2021-09-03 21:21 UTC, indifferentghost commented
>     1. We are wondering how data will be passed from MDX markdown to JSON and back to MD when creating, and editing posts. Will that require some sort of config, like a YAML file?

- We won't be using much of the `x` of MDX to start with, the markdown will be a string stored in the DB.

>     1. Do we need a dedicated Header component?

- I'm leaving this up to you we can always change it later

>     1. We haven't styled the components. We figured we should establish some sort of standard as a group, and create styling specific tickets. What do you think?

- We discussed this in the discord the TL;DR is that we're using [styled-components](https://styled-components.com/) as a middle ground between writing your own css and having nice features that don't normally come with css.

2021-09-08 03:14 UTC, indifferentghost requested changes

2021-09-08 03:14 UTC, indifferentghost commented on packages/client/package.json
> +    "babel-loader": "^8.1.0"
These aren't really dev dependencies since they're needed for the build. devDependencies are almost exclusively linting.

2021-09-08 03:14 UTC, indifferentghost commented on packages/client/src/components/Post.js
> +                }
```suggestion
                ) }
```

2021-09-10 21:24 UTC, indifferentghost requested changes
Looks good! Few suggested changes ping me when you've reviewed.

2021-09-10 21:24 UTC, indifferentghost commented on packages/client/src/components/Post.js
> +    }
We can move this to styled-components. Not something that _really_ matters. Example:
```js
const CollapsableDiv = styled.div`
  {({ hidden }) => {
    if (hidden) {
      return `transform: scaleY(0);
      transform-origin: top;`;
    }
  }}
`;
```

2021-09-10 21:24 UTC, indifferentghost commented on packages/client/src/components/Post.js
> +    }
Even if you decide this is better let's move the styles outside of the component else these styles will be recreated  every rerender of the post

2021-09-10 21:24 UTC, indifferentghost commented on packages/client/src/App.js
> +        </Post>
This will be different later on might want to add a note here to remove when we're bringing data.

2021-09-14 20:00 UTC, bjorkypie commented
Still need to figure out the markdown renderer, and what happens when the post is being edited, but we think the rest of the ticket is ok?

2021-09-14 20:25 UTC, indifferentghost commented
> Still need to figure out the markdown renderer, and what happens when the post is being edited, but we think the rest of the ticket is ok?

Editing is a different ticket.

2021-09-14 20:27 UTC, indifferentghost approved these changes

2021-09-15 19:44 UTC, merged