confirmed sessions is working
100devs/course-tracker pull request #48
Opened 2021-09-09 17:04 UTC by bjorkypie

confirmed sessions works with postman and mongo compass
added isAdmin to cookie
added session secret to env example
changed auth route endpoint in apiRoutes.js
removed unused 'new' variable in Post.js model

Are we on the right track for adding sessions?
Do we need some sort of middleware checking that the cookie matches the session stored in Mongo?

2021-09-10 21:17 UTC, indifferentghost requested changes
Small changes suggested, mostly cleanup looks good

2021-09-10 21:17 UTC, indifferentghost commented on packages/server/routes/authRoutes.js
> +
Let's clean this up
```suggestion
```

2021-09-10 21:17 UTC, indifferentghost commented on packages/server/routes/authRoutes.js
> +
Let's continue to clean this up:
```suggestion
```

2021-09-10 21:17 UTC, indifferentghost commented on packages/server/routes/authRoutes.js
>        console.log(_response);
Let's clean this up too
```suggestion
```

2021-09-10 21:17 UTC, indifferentghost commented on packages/server/routes/authRoutes.js
> +
continued clean up
```suggestion
```

2021-09-10 21:17 UTC, indifferentghost commented on packages/server/server.js
> +require("dotenv").config();
Nice catch, weird that it wasn't here.

You might want to move this to the top

2021-09-11 17:58 UTC, relspeedwagon approved these changes

2021-09-11 18:11 UTC, indifferentghost approved these changes

2021-09-11 19:45 UTC, merged