Task 67 add yarn.lock to .gitignore
100devs/course-tracker pull request #73
Opened 2021-09-25 21:53 UTC by JenniferToops

Added yarn.lock to .gitignore file

**Forgot to add Yolanda Haynes as a co-author in the commit. 

Co-Authored-By: Yolanda Haynes yhaynes@giyo.us

2021-09-26 23:39 UTC, indifferentghost requested changes
We should also delete the yarn.lock as well.

2021-09-27 19:09 UTC, JenniferToops commented
> We should also delete the yarn.lock as well.

I just removed yarn.lock from the root folder. 
To confirm: we don't actually need the yarn.lock folder in the repo since folx who fork/clone the repo for their own use will end up with their own copy at the time they yarn install, correct? Am I missing anything?
Thanks!

2021-09-27 20:23 UTC, indifferentghost commented
Correct this looks great!

2021-09-27 20:23 UTC, indifferentghost approved these changes

2021-09-27 21:54 UTC, merged